# Generated by Django 4.2.1 on 2023-05-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Yangiliklar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=232)),
                ("desc", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="news/%Y/%m/%d", null=True, upload_to=""
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
