# Generated by Django 4.2.1 on 2023-06-13 19:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newscartegory",
            name="name_en",
            field=models.CharField(blank=True, max_length=211, null=True),
        ),
        migrations.AddField(
            model_name="newscartegory",
            name="name_ru",
            field=models.CharField(blank=True, max_length=211, null=True),
        ),
        migrations.AddField(
            model_name="newscartegory",
            name="name_uz",
            field=models.CharField(blank=True, max_length=211, null=True),
        ),
        migrations.AddField(
            model_name="newscartegory",
            name="slug_en",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="newscartegory",
            name="slug_ru",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="newscartegory",
            name="slug_uz",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="yangiliklar",
            name="desc_en",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="yangiliklar",
            name="desc_ru",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="yangiliklar",
            name="desc_uz",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="yangiliklar",
            name="title_en",
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name="yangiliklar",
            name="title_ru",
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name="yangiliklar",
            name="title_uz",
            field=models.CharField(max_length=232, null=True),
        ),
    ]
