# Generated by Django 4.2.1 on 2023-05-15 15:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yangiliklar",
            name="desc",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
