# Generated by Django 4.2.1 on 2023-05-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_yangiliklar_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCartegory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=211)),
                ("slug", models.SlugField(unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="news.newscartegory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="yangiliklar",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="news.newscartegory",
            ),
            preserve_default=False,
        ),
    ]
