# Generated by Django 4.2.1 on 2023-07-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='thumnail',
            field=models.ImageField(default='', upload_to='thumnail/'),
            preserve_default=False,
        ),
    ]
