# Generated by Django 4.2.1 on 2023-06-01 06:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=233)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="banners/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=211)),
                ("slug", models.SlugField(unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="home.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=224)),
                ("desc", ckeditor.fields.RichTextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="content/%Y/%m/%d"
                    ),
                ),
                ("pdf", models.FileField(blank=True, null=True, upload_to="pdfsd/")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fakultetlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=224)),
                (
                    "summa",
                    models.DecimalField(decimal_places=0, default=0, max_digits=11),
                ),
            ],
            options={
                "verbose_name": "Fakultet",
                "verbose_name_plural": "Fakultetlar",
            },
        ),
        migrations.CreateModel(
            name="Kunduz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=224)),
                (
                    "summa",
                    models.DecimalField(decimal_places=0, default=0, max_digits=11),
                ),
            ],
            options={
                "verbose_name": "Kunduz",
                "verbose_name_plural": "Kunduzgilar",
            },
        ),
        migrations.CreateModel(
            name="Magistr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=224)),
                (
                    "summa",
                    models.DecimalField(decimal_places=0, default=0, max_digits=11),
                ),
            ],
            options={
                "verbose_name": "Magistr",
                "verbose_name_plural": "Magistrlar",
            },
        ),
        migrations.CreateModel(
            name="Malumotlar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=224)),
                ("desc", ckeditor.fields.RichTextField()),
                ("image", models.ImageField(upload_to="mailumotlar/%Y/%m/%d")),
            ],
        ),
        migrations.CreateModel(
            name="OqishniKochirish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", ckeditor.fields.RichTextField()),
            ],
            options={
                "verbose_name": "OqishniKochirish",
                "verbose_name_plural": "OqishniKochirishlar",
            },
        ),
        migrations.CreateModel(
            name="Rektorat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lavozim", models.CharField(blank=True, max_length=223)),
                ("desc", ckeditor.fields.RichTextField()),
                ("image", models.ImageField(upload_to="rektors/")),
            ],
        ),
        migrations.CreateModel(
            name="Sirtqi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=224)),
                (
                    "summa",
                    models.DecimalField(decimal_places=0, default=0, max_digits=11),
                ),
            ],
            options={
                "verbose_name": "Sirtqi",
                "verbose_name_plural": "Sirtqilar",
            },
        ),
        migrations.CreateModel(
            name="Talabalar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=224)),
                (
                    "summa",
                    models.DecimalField(decimal_places=0, default=0, max_digits=11),
                ),
            ],
            options={
                "verbose_name": "Talaba",
                "verbose_name_plural": "Talabalar",
            },
        ),
        migrations.CreateModel(
            name="MalImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="malconte/%Y/%m/%d"
                    ),
                ),
                (
                    "mal",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.malumotlar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="contents/%Y/%m/%d"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.content",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("pdf", models.FileField(upload_to="pdfs/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
            ],
        ),
    ]
