# Generated by Django 4.2.1 on 2023-06-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(blank=True, max_length=211, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_uz",
            field=models.CharField(blank=True, max_length=211, null=True),
        ),
    ]
