# Generated by Django 4.2.1 on 2023-06-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="level",
        ),
        migrations.RemoveField(
            model_name="content",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="content",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="content",
            name="tree_id",
        ),
    ]
