# Generated by Django 4.2.1 on 2023-06-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_content_level_remove_content_lft_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="malumotlar",
            name="level",
        ),
        migrations.RemoveField(
            model_name="malumotlar",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="malumotlar",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="malumotlar",
            name="tree_id",
        ),
    ]
