# Generated by Django 4.2.1 on 2023-06-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bannercha_delete_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercha',
            name='parent_id',
            field=models.CharField(default='1', max_length=123),
        ),
    ]
