# Generated by Django 4.2.1 on 2023-06-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_category_name_en_category_name_uz"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug_en",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="slug_uz",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
