# Generated by Django 4.2.1 on 2023-05-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="content/%Y/%m/%d"
            ),
        ),
    ]
