# Generated by Django 4.2.1 on 2023-06-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_banner_bannercha_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannercha',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
