# Generated by Django 4.2.1 on 2023-05-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_content_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fakultetlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=224)),
                (
                    "summa",
                    models.DecimalField(decimal_places=0, default=0, max_digits=11),
                ),
            ],
            options={
                "verbose_name": "Fakultet",
                "verbose_name_plural": "Fakultetlar",
            },
        ),
    ]
