# Generated by Django 4.2.1 on 2023-06-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_category_slug_en_category_slug_uz"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(blank=True, max_length=211, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="slug_ru",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
