# Generated by Django 4.2.1 on 2023-06-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_malumotlar_level_remove_malumotlar_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category_en',
            field=models.ManyToManyField(null=True, related_name='contents', to='home.category'),
        ),
        migrations.AddField(
            model_name='content',
            name='category_ru',
            field=models.ManyToManyField(null=True, related_name='contents', to='home.category'),
        ),
        migrations.AddField(
            model_name='content',
            name='category_uz',
            field=models.ManyToManyField(null=True, related_name='contents', to='home.category'),
        ),
        migrations.AddField(
            model_name='malumotlar',
            name='image_en',
            field=models.ImageField(null=True, upload_to='mailumotlar/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='malumotlar',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='mailumotlar/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='malumotlar',
            name='image_uz',
            field=models.ImageField(null=True, upload_to='mailumotlar/%Y/%m/%d'),
        ),
    ]
