# Generated by Django 4.2.1 on 2023-06-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_banner_rename_parent_id_bannercha_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercha',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.bannercha'),
        ),
    ]
