# Generated by Django 4.2.1 on 2023-05-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="contents/%Y/%m/%d"
            ),
        ),
    ]
