# Generated by Django 4.2.1 on 2023-06-14 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bannercha_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='content',
            name='category_uz',
        ),
        migrations.RemoveField(
            model_name='malumotlar',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='malumotlar',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='malumotlar',
            name='image_uz',
        ),
    ]
