# Generated by Django 4.2.1 on 2023-06-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_content_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakultetlar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fakultetlar',
            name='summa',
        ),
        migrations.AddField(
            model_name='fakultetlar',
            name='content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='home.content'),
        ),
    ]
