# Generated by Django 4.2.1 on 2023-05-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_images_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MalImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="contents/%Y/%m/%d"
                    ),
                ),
                (
                    "mal",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.malumotlar",
                    ),
                ),
            ],
        ),
    ]
