# Generated by Django 4.2.1 on 2023-05-30 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_malimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="malimages",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="malconte/%Y/%m/%d"
            ),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("pdf", models.FileField(upload_to="pdfs/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
            ],
        ),
    ]
