# Generated by Django 4.2.1 on 2023-06-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_fakultetlar_name_remove_fakultetlar_summa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='nomi',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='summa',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
