# Generated by Django 4.2.1 on 2023-05-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_malimages_image_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfsd/"),
        ),
    ]
