# Generated by Django 4.2.1 on 2023-06-14 09:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_content_nomi_alter_content_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='desc',
            field=ckeditor.fields.RichTextField(default='12'),
        ),
        migrations.AlterField(
            model_name='content',
            name='desc_en',
            field=ckeditor.fields.RichTextField(default='12', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(default='12', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='desc_uz',
            field=ckeditor.fields.RichTextField(default='12', null=True),
        ),
    ]
