# Generated by Django 4.2.1 on 2023-06-14 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_content_desc_rek_content_lavozim_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="rektor_image",
            new_name="rektorimage",
        ),
    ]
