# Generated by Django 4.2.1 on 2023-06-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_rektor_image_content_rektorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='nomi_en',
            field=models.CharField(blank=True, max_length=224, null=True, verbose_name='Fakultent Nomi'),
        ),
        migrations.AddField(
            model_name='content',
            name='nomi_ru',
            field=models.CharField(blank=True, max_length=224, null=True, verbose_name='Fakultent Nomi'),
        ),
        migrations.AddField(
            model_name='content',
            name='nomi_uz',
            field=models.CharField(blank=True, max_length=224, null=True, verbose_name='Fakultent Nomi'),
        ),
    ]
