# Generated by Django 4.2.1 on 2023-06-15 18:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_content_nomi_en_content_nomi_ru_content_nomi_uz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="desc_rek",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
