# Generated by Django 4.2.1 on 2023-06-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_content_desc_rek_alter_content_desc_rek_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=234)),
                ('image', models.ImageField(upload_to='sliders/%Y/%m')),
            ],
        ),
    ]
