# Generated by Django 4.2.1 on 2023-06-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='url_link',
            field=models.CharField(blank=True, default='https://u-ukm.uz/web/en', max_length=233, null=True),
        ),
    ]
